// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkkvzbvgnutafrholvvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxra3Z6YnZnbnV0YWZyaG9sdnZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MDc1NDAsImV4cCI6MjA1NTk4MzU0MH0.361YNv4sLa2j0wa0X-IiA7sScsCl2CdhujIUJzRyQh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);